/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.definitions;


import mathias.vanhack.skip.model.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>xprssdlvrydb</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index XD_FOOD_FD_FOOD_FD_RESTAURANT_REST_ID_FK = Indexes0.XD_FOOD_FD_FOOD_FD_RESTAURANT_REST_ID_FK;
    public static final Index XD_FOOD_FD_FOOD_FOOD_ID_UINDEX = Indexes0.XD_FOOD_FD_FOOD_FOOD_ID_UINDEX;
    public static final Index XD_FOOD_PRIMARY = Indexes0.XD_FOOD_PRIMARY;
    public static final Index XD_ORDER_PRIMARY = Indexes0.XD_ORDER_PRIMARY;
    public static final Index XD_ORDER_XD_ORDER_ORDER_ID_UINDEX = Indexes0.XD_ORDER_XD_ORDER_ORDER_ID_UINDEX;
    public static final Index XD_ORDER_XD_ORDER_XD_RESTAURANT_REST_ID_FK = Indexes0.XD_ORDER_XD_ORDER_XD_RESTAURANT_REST_ID_FK;
    public static final Index XD_ORDER_XD_ORDER_XD_USER_USER_ID_FK = Indexes0.XD_ORDER_XD_ORDER_XD_USER_USER_ID_FK;
    public static final Index XD_ORDER_FOOD_PRIMARY = Indexes0.XD_ORDER_FOOD_PRIMARY;
    public static final Index XD_ORDER_FOOD_XD_ORDER_FOOD_ORDER_FOOD_ID_UINDEX = Indexes0.XD_ORDER_FOOD_XD_ORDER_FOOD_ORDER_FOOD_ID_UINDEX;
    public static final Index XD_ORDER_FOOD_XD_ORDER_FOOD_ORDER_ID_UINDEX = Indexes0.XD_ORDER_FOOD_XD_ORDER_FOOD_ORDER_ID_UINDEX;
    public static final Index XD_ORDER_FOOD_XD_ORDER_FOOD_XD_FOOD_FOOD_ID_FK = Indexes0.XD_ORDER_FOOD_XD_ORDER_FOOD_XD_FOOD_FOOD_ID_FK;
    public static final Index XD_RESTAURANT_FD_RESTAURANT_REST_ID_UINDEX = Indexes0.XD_RESTAURANT_FD_RESTAURANT_REST_ID_UINDEX;
    public static final Index XD_RESTAURANT_PRIMARY = Indexes0.XD_RESTAURANT_PRIMARY;
    public static final Index XD_USER_PRIMARY = Indexes0.XD_USER_PRIMARY;
    public static final Index XD_USER_XD_USER_USER_ID_UINDEX = Indexes0.XD_USER_XD_USER_USER_ID_UINDEX;
    public static final Index XD_USER_XD_USER_USERNAME_UINDEX = Indexes0.XD_USER_XD_USER_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index XD_FOOD_FD_FOOD_FD_RESTAURANT_REST_ID_FK = Internal.createIndex("fd_food_fd_restaurant_rest_id_fk", FoodTable.XD_FOOD, new OrderField[]{FoodTable.XD_FOOD.REST_ID}, false);
        public static Index XD_FOOD_FD_FOOD_FOOD_ID_UINDEX = Internal.createIndex("fd_food_food_id_uindex", FoodTable.XD_FOOD, new OrderField[]{FoodTable.XD_FOOD.FOOD_ID}, true);
        public static Index XD_FOOD_PRIMARY = Internal.createIndex("PRIMARY", FoodTable.XD_FOOD, new OrderField[]{FoodTable.XD_FOOD.FOOD_ID}, true);
        public static Index XD_ORDER_PRIMARY = Internal.createIndex("PRIMARY", OrderTable.XD_ORDER, new OrderField[]{OrderTable.XD_ORDER.ORDER_ID}, true);
        public static Index XD_ORDER_XD_ORDER_ORDER_ID_UINDEX = Internal.createIndex("xd_order_order_id_uindex", OrderTable.XD_ORDER, new OrderField[]{OrderTable.XD_ORDER.ORDER_ID}, true);
        public static Index XD_ORDER_XD_ORDER_XD_RESTAURANT_REST_ID_FK = Internal.createIndex("xd_order_xd_restaurant_rest_id_fk", OrderTable.XD_ORDER, new OrderField[]{OrderTable.XD_ORDER.REST_ID}, false);
        public static Index XD_ORDER_XD_ORDER_XD_USER_USER_ID_FK = Internal.createIndex("xd_order_xd_user_user_id_fk", OrderTable.XD_ORDER, new OrderField[]{OrderTable.XD_ORDER.USER_ID}, false);
        public static Index XD_ORDER_FOOD_PRIMARY = Internal.createIndex("PRIMARY", OrderFoodTable.XD_ORDER_FOOD, new OrderField[]{OrderFoodTable.XD_ORDER_FOOD.ORDER_FOOD_ID}, true);
        public static Index XD_ORDER_FOOD_XD_ORDER_FOOD_ORDER_FOOD_ID_UINDEX = Internal.createIndex("xd_order_food_order_food_id_uindex", OrderFoodTable.XD_ORDER_FOOD, new OrderField[]{OrderFoodTable.XD_ORDER_FOOD.ORDER_FOOD_ID}, true);
        public static Index XD_ORDER_FOOD_XD_ORDER_FOOD_ORDER_ID_UINDEX = Internal.createIndex("xd_order_food_order_id_uindex", OrderFoodTable.XD_ORDER_FOOD, new OrderField[]{OrderFoodTable.XD_ORDER_FOOD.ORDER_ID}, true);
        public static Index XD_ORDER_FOOD_XD_ORDER_FOOD_XD_FOOD_FOOD_ID_FK = Internal.createIndex("xd_order_food_xd_food_food_id_fk", OrderFoodTable.XD_ORDER_FOOD, new OrderField[]{OrderFoodTable.XD_ORDER_FOOD.FOOD_ID}, false);
        public static Index XD_RESTAURANT_FD_RESTAURANT_REST_ID_UINDEX = Internal.createIndex("fd_restaurant_rest_id_uindex", RestaurantTable.XD_RESTAURANT, new OrderField[]{RestaurantTable.XD_RESTAURANT.REST_ID}, true);
        public static Index XD_RESTAURANT_PRIMARY = Internal.createIndex("PRIMARY", RestaurantTable.XD_RESTAURANT, new OrderField[]{RestaurantTable.XD_RESTAURANT.REST_ID}, true);
        public static Index XD_USER_PRIMARY = Internal.createIndex("PRIMARY", UserTable.XD_USER, new OrderField[]{UserTable.XD_USER.USER_ID}, true);
        public static Index XD_USER_XD_USER_USER_ID_UINDEX = Internal.createIndex("xd_user_user_id_uindex", UserTable.XD_USER, new OrderField[]{UserTable.XD_USER.USER_ID}, true);
        public static Index XD_USER_XD_USER_USERNAME_UINDEX = Internal.createIndex("xd_user_username_uindex", UserTable.XD_USER, new OrderField[]{UserTable.XD_USER.USERNAME}, true);
    }
}
