/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.definitions;


import mathias.vanhack.skip.model.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in xprssdlvrydb
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>xprssdlvrydb.xd_food</code>.
     */
    public static final FoodTable XD_FOOD = mathias.vanhack.skip.model.tables.FoodTable.XD_FOOD;

    /**
     * The table <code>xprssdlvrydb.xd_order</code>.
     */
    public static final OrderTable XD_ORDER = mathias.vanhack.skip.model.tables.OrderTable.XD_ORDER;

    /**
     * The table <code>xprssdlvrydb.xd_order_food</code>.
     */
    public static final OrderFoodTable XD_ORDER_FOOD = mathias.vanhack.skip.model.tables.OrderFoodTable.XD_ORDER_FOOD;

    /**
     * The table <code>xprssdlvrydb.xd_restaurant</code>.
     */
    public static final RestaurantTable XD_RESTAURANT = mathias.vanhack.skip.model.tables.RestaurantTable.XD_RESTAURANT;

    /**
     * The table <code>xprssdlvrydb.xd_user</code>.
     */
    public static final UserTable XD_USER = mathias.vanhack.skip.model.tables.UserTable.XD_USER;
}
