/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.definitions;


import mathias.vanhack.skip.model.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Xprssdlvrydb extends SchemaImpl {

    private static final long serialVersionUID = -1981803424;

    /**
     * The reference instance of <code>xprssdlvrydb</code>
     */
    public static final Xprssdlvrydb XPRSSDLVRYDB = new Xprssdlvrydb();

    /**
     * The table <code>xprssdlvrydb.xd_food</code>.
     */
    public final FoodTable XD_FOOD = mathias.vanhack.skip.model.tables.FoodTable.XD_FOOD;

    /**
     * The table <code>xprssdlvrydb.xd_order</code>.
     */
    public final OrderTable XD_ORDER = mathias.vanhack.skip.model.tables.OrderTable.XD_ORDER;

    /**
     * The table <code>xprssdlvrydb.xd_order_food</code>.
     */
    public final OrderFoodTable XD_ORDER_FOOD = mathias.vanhack.skip.model.tables.OrderFoodTable.XD_ORDER_FOOD;

    /**
     * The table <code>xprssdlvrydb.xd_restaurant</code>.
     */
    public final RestaurantTable XD_RESTAURANT = mathias.vanhack.skip.model.tables.RestaurantTable.XD_RESTAURANT;

    /**
     * The table <code>xprssdlvrydb.xd_user</code>.
     */
    public final UserTable XD_USER = mathias.vanhack.skip.model.tables.UserTable.XD_USER;

    /**
     * No further instances allowed
     */
    private Xprssdlvrydb() {
        super("xprssdlvrydb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                FoodTable.XD_FOOD,
                OrderTable.XD_ORDER,
                OrderFoodTable.XD_ORDER_FOOD,
                RestaurantTable.XD_RESTAURANT,
                UserTable.XD_USER);
    }
}
