/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.records;


import mathias.vanhack.skip.model.tables.FoodTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FoodRecord extends UpdatableRecordImpl<FoodRecord> implements Record5<Integer, String, String, Double, Integer> {

    private static final long serialVersionUID = 426791759;

    /**
     * Setter for <code>xprssdlvrydb.xd_food.food_id</code>.
     */
    public void setFoodId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_food.food_id</code>.
     */
    public Integer getFoodId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_food.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_food.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_food.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_food.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_food.price</code>.
     */
    public void setPrice(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_food.price</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_food.rest_id</code>.
     */
    public void setRestId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_food.rest_id</code>.
     */
    public Integer getRestId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Double, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Double, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FoodTable.XD_FOOD.FOOD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FoodTable.XD_FOOD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FoodTable.XD_FOOD.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return FoodTable.XD_FOOD.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return FoodTable.XD_FOOD.REST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFoodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getRestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFoodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoodRecord value1(Integer value) {
        setFoodId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoodRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoodRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoodRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoodRecord value5(Integer value) {
        setRestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoodRecord values(Integer value1, String value2, String value3, Double value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FoodRecord
     */
    public FoodRecord() {
        super(FoodTable.XD_FOOD);
    }

    /**
     * Create a detached, initialised FoodRecord
     */
    public FoodRecord(Integer foodId, String name, String description, Double price, Integer restId) {
        super(FoodTable.XD_FOOD);

        set(0, foodId);
        set(1, name);
        set(2, description);
        set(3, price);
        set(4, restId);
    }
}
