/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.records;


import mathias.vanhack.skip.model.tables.OrderTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record8<Integer, LocalDateTime, Integer, Integer, String, Double, String, Double> {

    private static final long serialVersionUID = -478502056;

    /**
     * Setter for <code>xprssdlvrydb.xd_order.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_order.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_order.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_order.rest_id</code>.
     */
    public void setRestId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.rest_id</code>.
     */
    public Integer getRestId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_order.order_status</code>.
     */
    public void setOrderStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.order_status</code>.
     */
    public String getOrderStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_order.total_price</code>.
     */
    public void setTotalPrice(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.total_price</code>.
     */
    public Double getTotalPrice() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_order.payment_type</code>.
     */
    public void setPaymentType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.payment_type</code>.
     */
    public String getPaymentType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xprssdlvrydb.xd_order.delivery_fee</code>.
     */
    public void setDeliveryFee(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>xprssdlvrydb.xd_order.delivery_fee</code>.
     */
    public Double getDeliveryFee() {
        return (Double) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, LocalDateTime, Integer, Integer, String, Double, String, Double> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, LocalDateTime, Integer, Integer, String, Double, String, Double> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderTable.XD_ORDER.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return OrderTable.XD_ORDER.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrderTable.XD_ORDER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OrderTable.XD_ORDER.REST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OrderTable.XD_ORDER.ORDER_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return OrderTable.XD_ORDER.TOTAL_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return OrderTable.XD_ORDER.PAYMENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return OrderTable.XD_ORDER.DELIVERY_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component2() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getRestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getTotalPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getDeliveryFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getTotalPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getDeliveryFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value1(Integer value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value2(LocalDateTime value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value4(Integer value) {
        setRestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value5(String value) {
        setOrderStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value6(Double value) {
        setTotalPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value7(String value) {
        setPaymentType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value8(Double value) {
        setDeliveryFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord values(Integer value1, LocalDateTime value2, Integer value3, Integer value4, String value5, Double value6, String value7, Double value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(OrderTable.XD_ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Integer orderId, LocalDateTime dateCreated, Integer userId, Integer restId, String orderStatus, Double totalPrice, String paymentType, Double deliveryFee) {
        super(OrderTable.XD_ORDER);

        set(0, orderId);
        set(1, dateCreated);
        set(2, userId);
        set(3, restId);
        set(4, orderStatus);
        set(5, totalPrice);
        set(6, paymentType);
        set(7, deliveryFee);
    }
}
