/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Food implements Serializable {

    private static final long serialVersionUID = 2125476384;

    private Integer foodId;
    private String name;
    private String description;
    private Double price;
    private Integer restId;

    public Food() {
    }

    public Food(Food value) {
        this.foodId = value.foodId;
        this.name = value.name;
        this.description = value.description;
        this.price = value.price;
        this.restId = value.restId;
    }

    public Food(
            Integer foodId,
            String name,
            String description,
            Double price,
            Integer restId
    ) {
        this.foodId = foodId;
        this.name = name;
        this.description = description;
        this.price = price;
        this.restId = restId;
    }

    public Integer getFoodId() {
        return this.foodId;
    }

    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getRestId() {
        return this.restId;
    }

    public void setRestId(Integer restId) {
        this.restId = restId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Food (");

        sb.append(foodId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(price);
        sb.append(", ").append(restId);

        sb.append(")");
        return sb.toString();
    }
}
