/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.pojos;


import mathias.vanhack.skip.enums.OrderStatus;
import mathias.vanhack.skip.enums.PaymentType;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Order implements Serializable {

    private static final long serialVersionUID = 666693224;

    private Integer orderId;
    private LocalDateTime dateCreated;
    private Integer userId;
    private Integer restId;
    private OrderStatus orderStatus;
    private Double totalPrice;
    private PaymentType paymentType;
    private Double deliveryFee;

    private List<OrderFood> orderFoods;

    public Order() {
    }

    public Order(Order value) {
        this.orderId = value.orderId;
        this.dateCreated = value.dateCreated;
        this.userId = value.userId;
        this.restId = value.restId;
        this.orderStatus = value.orderStatus;
        this.totalPrice = value.totalPrice;
        this.paymentType = value.paymentType;
        this.deliveryFee = value.deliveryFee;
    }

    public Order(
            Integer orderId,
            LocalDateTime dateCreated,
            Integer userId,
            Integer restId,
            OrderStatus orderStatus,
            Double totalPrice,
            PaymentType paymentType,
            Double deliveryFee
    ) {
        this.orderId = orderId;
        this.dateCreated = dateCreated;
        this.userId = userId;
        this.restId = restId;
        this.orderStatus = orderStatus;
        this.totalPrice = totalPrice;
        this.paymentType = paymentType;
        this.deliveryFee = deliveryFee;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public LocalDateTime getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRestId() {
        return this.restId;
    }

    public void setRestId(Integer restId) {
        this.restId = restId;
    }

    public OrderStatus getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Double getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    public PaymentType getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

    public Double getDeliveryFee() {
        return this.deliveryFee;
    }

    public void setDeliveryFee(Double deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    public List<OrderFood> getOrderFoods() {
        return orderFoods;
    }

    public void setOrderFoods(List<OrderFood> orderFoods) {
        this.orderFoods = orderFoods;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(orderId);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(userId);
        sb.append(", ").append(restId);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(totalPrice);
        sb.append(", ").append(paymentType);
        sb.append(", ").append(deliveryFee);

        sb.append(")");
        return sb.toString();
    }
}
