/*
 * This file is generated by jOOQ.
 */
package mathias.vanhack.skip.model.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OrderFood implements Serializable {

    private static final long serialVersionUID = 1012280310;

    private Integer orderFoodId;
    private Integer orderId;
    private Integer foodId;
    private Integer amount;
    private Double price;

    private Food food;

    public OrderFood() {
    }

    public OrderFood(OrderFood value) {
        this.orderFoodId = value.orderFoodId;
        this.orderId = value.orderId;
        this.foodId = value.foodId;
        this.amount = value.amount;
        this.price = value.price;
    }

    public OrderFood(
            Integer orderFoodId,
            Integer orderId,
            Integer foodId,
            Integer amount,
            Double price
    ) {
        this.orderFoodId = orderFoodId;
        this.orderId = orderId;
        this.foodId = foodId;
        this.amount = amount;
        this.price = price;
    }

    public Integer getOrderFoodId() {
        return this.orderFoodId;
    }

    public void setOrderFoodId(Integer orderFoodId) {
        this.orderFoodId = orderFoodId;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getFoodId() {
        return this.foodId;
    }

    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Food getFood() {
        return food;
    }

    public void setFood(Food food) {
        this.food = food;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderFood (");

        sb.append(orderFoodId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(foodId);
        sb.append(", ").append(amount);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
